# Generated by Django 5.2.8 on 2025-11-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('destinoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('pais', models.CharField(max_length=100)),
                ('moneda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('viajeID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('plazas_disponibles', models.IntegerField()),
                ('plazas_totales', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAgenciaDjango.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('seguro_viaje', models.BooleanField(default=False)),
                ('clienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAgenciaDjango.cliente')),
                ('viajeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAgenciaDjango.viaje')),
            ],
        ),
    ]
