# Generated by Django 5.2.8 on 2025-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAgenciaDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='plazas_disponibles',
        ),
    ]
