# Generated by Django 5.2.7 on 2025-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAgenciaDjango', '0002_remove_viaje_plazas_disponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('reseña', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino_viajado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
